pipeline {
    agent any
    tools{
        jdk 'OpenJDK8'
        maven 'jenkins-maven'
        
    }

    triggers {
        githubPush()  
        pollSCM('* * * * *')
    }

    stages {
        stage('SCM') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/the-one-rvs/elevate-8.git'
            }
        }
        stage('Build Maven') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage ('Docker build') {
            steps {
                sh "docker build -t quasarcelestio/java-example:latest . "
            }
        }
        stage('Docker Push to Docker Hub') {
            steps {
                script{
                    withDockerRegistry(credentialsId: 'dockerhubcred') {
                        // some block
                        sh "docker push  quasarcelestio/java-example:latest"
                    }
                }
            }
        }
    }
}
