pipeline {
    agent any
    tools{
        jdk 'OpenJDK9'
        maven 'jenkins-maven'
        
    }
    environment {
        JAVA_HOME = tool 'OpenJDK9'
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }

    stages {
        stage('SCM') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/the-one-rvs/docker-spring-boot-java-web-service-example'
            }
        }
        stage('Build Maven') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Docker build and run') {
            steps {
                script{
                    withDockerRegistry(credentialsId: 'docker-hub-credentials') {
                        // some block
                        sh "docker build -t quasarcelestio/example:latest . "
                        sh "docker push  quasarcelestio/example:latest"
                    }
                }
            }
        }
    }
}
